apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: redisinsight-pvc
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: redis-insight
spec:
  replicas: 1
  selector:
    matchLabels:
      app: redis-insight
  template:
    metadata:
      labels:
        app: redis-insight
    spec:
      containers:
        - name: redis-insight
          image: redis/redisinsight:latest
          ports:
            - containerPort: 5540
          volumeMounts:
            - name: redisinsight-data
              mountPath: /data
      volumes:
        - name: redisinsight-data
          persistentVolumeClaim:
            claimName: redisinsight-pvc
---
apiVersion: v1
kind: Service
metadata:
  name: redis-insight
spec:
  type: NodePort
  selector:
    app: redis-insight
  ports:
    - name: http
      port: 80
      targetPort: 5540
      nodePort: 30081   # must be in 30000–32767 range